aws:
  base-endpoint: "${AWS_BASE_ENDPOINT}"

attachments:
  base-path: "${ATTACHMENTS_BASE_PATH}"

payload-storage:
  path: "${PAYLOAD_STORAGE_PATH}"

outbox:
  table-name: "${EMAIL_OUTBOX_TABLE}"
  stale-emails-threshold-minutes: 30

server:
  port: 8080
