mysql:
  host: "${MYSQL_HOST}"
  port: ${MYSQL_PORT}
  user: "${MYSQL_USER}"
  password: "${MYSQL_PASSWORD}"
  database: "${MYSQL_DATABASE}"

payload-storage:
  path: "${PAYLOAD_STORAGE_PATH}"

outbox:
  stale-emails-threshold-minutes: 30

server:
  port: 8080
