aws:
  base-endpoint: "${AWS_BASE_ENDPOINT}"

attachments:
  base-path: "${ATTACHMENTS_BASE_PATH}"

eml-storage:
  path: "${EML_STORAGE_PATH}"

payload-storage:
  path: "${PAYLOAD_STORAGE_PATH}"

outbox:
  table-name: "${EMAIL_OUTBOX_TABLE}"

server:
  port: 8080
